language: ruby
script: ./ci/cibuild.sh
rvm:
  - 2.3
before_install:
  - gem update --system
  - gem install bundler
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler
notifications:
  email: false
