version: '3'
services:
  ci:
    build:
      context: .
      args:
        build_user: root
    volumes:
      - ${SOURCES_DIRECTORY}:/app
      - ${BINARIES_DIRECTORY}:/site
    command: bash /app/docker-ci.sh
    environment:
      - DESTINATION=/site
