version: '3'
services:
  web:
    tty: true
    stdin_open: true
    image: jekyll/builder:latest
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    working_dir: /app
    command: ./docker-start.sh
